#!/bin/sh

# ======================================================================
# .bash_profile: VAGRANT VERSION
# ======================================================================

export HISTFILESIZE=100000

if [[ $PATH != *"$HOME/bin"* ]]; then
    export PATH=$HOME/bin:$PATH
fi

source_files()
{
  local file

  for file in "$@" ; do

    file=${file/\~\//$HOME\/} # Expand ~/

    if [[ -s "${file}" ]] ; then
      source "${file}"
    else
      if [[ ! -e "${file}" ]] ; then
        printf "NOTICE: ${file} does not exist, not loading.\n"
      else
        true # simply an empty file, no warning necessary.
      fi
    fi
  done

  return 0
}

source_files ~/.aliases \
  ~/.bash_completions \
  ~/code/vagrant_bin/ps1_functions \
  ~/.bash_functions \
  ~/.current-project \
  /home/vagrant/.nix-profile/etc/profile.d/nix.sh

# these must come after nix.sh has been sourced so that emacs is in PATH
export EDITOR=$(echo `which emacs` -q -l ~/.emacstiny)
export GEMEDITOR=$(echo `which emacs`)


# this must come after git-completion.bash has been sourced
# turn on path completion for go
complete -o default -o nospace -F _git_checkout go

if command -v ps1_set >/dev/null 2>&1 ; then
    ps1_set --prompt ∫
else
    export PS1="!!! It's \D{%H} O'Clock! Time to install rvm to fix your prompt!\n$ "
fi

ssh-add
